export const INSERT_NEWSLETTER_EMAIL_ENDPOINT = process.env
  .INSERT_NEWSLETTER_EMAIL_ENDPOINT as string;

export const GET_NEWSLETTER_SUBSCRIBER_ENDPOINT = process.env
  .GET_NEWSLETTER_SUBSCRIBER_ENDPOINT as string;
